[project]
name = "quadrupole"
version = "0.1.0"
description = "Classes for reading and manipulating molecular quadrupole moments"
readme = "README.md"
authors = [
    { name = "Brock Dyer", email = "brockdyer03@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
